name: ManHunt
version: 1.0
main: me.brandonjja.manhunt.ManHunt
author: Brandonjja
description: Can you beat the game before you get hunted?
commands:
    setrole:
        usage: /setrole <roleName>
    role:
        usage: /role
    who:
        usage: /who
    pause:
        usage: /pause
    p:
        usage: /p